### ISSUE TITLE
Modify naming and attributes of time variables on history files to be consistent with other CESM components

### ISSUE THREAD

**Issue by phillips-ad** [ESCOMP/CESM_CICE#14]
These changes are being requested to improve the ease-of-access of CESM data and to normalize the look of the metadata across CESM components. See https://github.com/ESCOMP/CESM/issues/194 and especially the google doc referenced from https://github.com/ESCOMP/CESM/issues/194#issuecomment-961443965

Current CICE time array output:

    float time(time) ;
		time:long_name = "model time" ;
		time:units = "days since 0001-01-01 00:00:00" ;
		time:calendar = "noleap" ;
		time:bounds = "time_bounds" ;
	float time_bounds(time, d2) ;
		time_bounds:long_name = "boundaries for time-averaging interval" ;
		time_bounds:units = "days since 0001-01-01 00:00:00" ;

Proposed CICE time array output:

	double time(time) ;
		time:long_name = "time" ;
		time:units = "days since 0001-01-01 00:00:00" ;
		time:calendar = "noleap" ;
		time:bounds = "time_bounds" ;
	double time_bounds(time, nbnd) ;
		time_bounds:long_name = "time interval endpoints" ;
		time_bounds:units = "days since 0001-01-01 00:00:00" ;
            time_bounds:calendar = "noleap" ;

Changes made: Change time/time_bounds to type double, add calendar attribute to time_bounds, change 2nd dimension name of time_bounds to nbnd, change time@long_name to “time”, change time_bounds@long_name to "time interval endpoints"

@billsacks @phillips-ad @strandwg are filing similar issues for each component.

**Comment by dabail10** [comment]
Resolved in cice6_4_1_8.
