### ISSUE TITLE
Set time value for averaged quantities to midpoint of averaging period

### ISSUE THREAD

**Issue by phillips-ad** [ESCOMP/CESM_CICE#15]
This is linked to https://github.com/ESCOMP/CAM/issues/159 and https://github.com/ESCOMP/CTSM/issues/1059, and involves setting the CICE output time value to the center of the averaging period. Different components may end up handling output differently, but the going consensus so far is to separate instantaneous data streams from averaged/min/max data streams.

Currently, the only component where time is set to the center of the averaging period is MOM.

**Comment by dabail10** [comment]
So, this is an easy thing to add the time axis of the middle of the averaging period. This is just the average of time_beg and time_end. However, the more complicated issue is the filenames. The filenames have a string which is YYYY-MM-DD-SSSSS. So, I would have to store a string for the middle of the averaging period. This is more complicated.

**Comment by dabail10** [comment]
I have added the namelist variable hist_time_axis and the default will be 'middle' for CESM_CICE.
