### ISSUE TITLE
Buildconf/cice.input_data_list incomplete 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CESM_CICE#19]
In testing case SMS_D.ne30pg3_g17.B1850.gust_intel I found that file
 ice_ic = "/glade/p/cesmdata/inputdata/ice/cice/b.e15.B1850G.f09_g16.pi_control.25.cice.r.0041-01-01-00000.nc"
is not listed in cice.input_data_list and thus will not be automatically downloaded

**Comment by dabail10** [comment]
This is weird. The ice_ic is set correctly in namelist_definition_cice.xml, but there a a bunch of files of the form:

b.e15.B1850G.f09_g16.pi_control.25.cice.r.0041-01-01-00000.nc-nnnnnnnnnn-nnnnn.lock

The original is still there, and should be in the inputdata svn site? I need to ask Chris about this.

**Comment by jedwards4b** [comment]
The issue isn't that the file is not in input data, it is there.  The issue is that the file isn't listed in the cice.input_data_list in the Buildconf sub-directory of the case.   This is the definitive list of input files required for the model and if a file is not listed there it will not be automatically downloaded.

**Comment by dabail10** [comment]
This sounds like an issue with check_input_data no? The files is in namelist_definition_cice.xml. What is the grid combination?
