### ISSUE TITLE
python imp module removed in version 3.12

### ISSUE THREAD

**Issue by brian-eaton** [ESCOMP/CESM_CICE#26]
I get failures from both `buildnml` and `buildlib` when trying to build F compsets using python-3.12.  A web search indicates that the imp module was deprecated in 3.11 and removed from 3.12.  Neither `buildnml` nor `buildlib` actually use the imp module.  The simple solution is to just remove it from the import statements in both scripts.

**Comment by dabail10** [comment]
Thanks for the note. I will get a fix soon.

**Comment by dabail10** [comment]
I have fixed this in cesm3_cice6_5_0_8.
